import express from "express";
import {
  getForecastEvents,
  createForecastEvent,
  updateForecastEvent,
  deleteForecastEvent,
  reconcileForecastEvent,
  unreconcileForecastEvent,
} from "../controllers/forecastEventController.js";
import { parse } from "csv-parse/sync";
import ForecastEvent from "../models/forecastEventModel.js";

const parseMoney = (v) =>
  Number(String(v || "").replace(/[£,]/g, "").trim()) || 0;

const parseCsvDate = (v) => {
  if (!v) return null;

  const raw = String(v).trim();

  // handles 30/05/2026
  const dmy = raw.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);
  if (dmy) {
    return new Date(`${dmy[3]}-${dmy[2].padStart(2, "0")}-${dmy[1].padStart(2, "0")}T00:00:00.000Z`);
  }

  // handles 30-May-2026
  const parsed = new Date(raw);
  return Number.isNaN(parsed.getTime()) ? null : parsed;
};

const forecastEventRouter = express.Router();

forecastEventRouter.get("/", getForecastEvents);
forecastEventRouter.post("/", createForecastEvent);
forecastEventRouter.put("/:id", updateForecastEvent);
forecastEventRouter.delete("/:id", deleteForecastEvent);

forecastEventRouter.post("/:id/reconcile", reconcileForecastEvent);
forecastEventRouter.post("/:id/unreconcile", unreconcileForecastEvent);


forecastEventRouter.post("/forecast-events/bulk-supplier-payouts-csv", async (req, res) => {
  try {
    const { csv, entity = "BMM", replaceExisting = false } = req.body || {};

    if (!csv || typeof csv !== "string") {
      return res.status(400).json({
        success: false,
        message: "CSV string is required in req.body.csv",
      });
    }

    const records = parse(csv, {
      columns: true,
      skip_empty_lines: true,
      trim: true,
      bom: true,
    });

    const docs = [];
    const errors = [];

    for (const [index, row] of records.entries()) {
      try {
        const bookingRef = String(row.bookingRef || "").trim();
        const supplierName = String(
          row.supplierName ||
            row.musicianName ||
            row["DJing in Buckinghamshire £252"] ||
            ""
        ).trim();

        const amount = parseMoney(row.Fee || row.fee || row.amount);
        const expectedDate = parseCsvDate(
          row["Date of transaction"] || row.expectedDate
        );
        const eventDate = parseCsvDate(row.eventDateISO || row.eventDate);

        if (!supplierName) throw new Error("Missing supplier name");
        if (!amount) throw new Error("Missing/invalid Fee");
        if (!expectedDate) throw new Error("Missing/invalid Date of transaction");

        docs.push({
          entity,
          type: "supplier_payment_out",
          title: `Supplier payout - ${supplierName}`,
          description: bookingRef
            ? `Supplier payout for booking ${bookingRef}`
            : "Supplier payout",
          expectedDate,
          amount: Math.abs(amount),
          direction: "out",
          status: "forecast",
          source: "supplier_payout_csv",
          clientNames: String(row.clientFirstNames || "").trim(),
          actName: "",
          eventDate,
          isAutoGenerated: false,
          notes: [
            bookingRef ? `Booking ref: ${bookingRef}` : "",
            eventDate ? `Event date: ${eventDate.toISOString().slice(0, 10)}` : "",
            `Supplier: ${supplierName}`,
          ]
            .filter(Boolean)
            .join("\n"),
        });
      } catch (err) {
        errors.push({
          row: index + 2,
          error: err.message,
          raw: row,
        });
      }
    }

    if (replaceExisting) {
      await ForecastEvent.deleteMany({
        source: "supplier_payout_csv",
        entity,
        isAutoGenerated: false,
      });
    }

    const inserted = docs.length ? await ForecastEvent.insertMany(docs) : [];

    return res.json({
      success: errors.length === 0,
      totalRows: records.length,
      imported: inserted.length,
      failed: errors.length,
      errors,
      preview: inserted.slice(0, 5),
    });
  } catch (err) {
    console.error("bulk supplier payouts csv error:", err);
    return res.status(500).json({
      success: false,
      message: err.message || "Bulk import failed",
    });
  }
});

export default forecastEventRouter;