import BookingForecast from "../models/bookingForecastModel.js";
import ForecastEvent from "../models/forecastEventModel.js";
import generateForecastEventsFromBooking from "../utils/generateForecastEventsFromBooking.js";

export const createBookingForecast = async (req, res) => {
  try {
    const booking = await BookingForecast.create(req.body);

    const forecastEvents = generateForecastEventsFromBooking(booking);

    if (forecastEvents.length) {
      await ForecastEvent.insertMany(forecastEvents);
    }

    res.status(201).json({
      success: true,
      booking,
      forecastEventsCreated: forecastEvents.length,
    });
  } catch (error) {
    console.error("createBookingForecast error:", error);
    res.status(500).json({
      success: false,
      message: error.message,
    });
  }
};

export const updateBookingForecast = async (req, res) => {
  try {
    const { id } = req.params;

    const booking = await BookingForecast.findByIdAndUpdate(id, req.body, {
      new: true,
      runValidators: true,
    });

    if (!booking) {
      return res.status(404).json({
        success: false,
        message: "Booking forecast not found",
      });
    }

    // Delete old auto-generated forecast events for this booking
    await ForecastEvent.deleteMany({
      bookingForecastId: booking._id,
      isAutoGenerated: true,
      status: { $in: ["forecast", "confirmed"] },
    });

    // Recreate updated forecast events
    const forecastEvents = generateForecastEventsFromBooking(booking);

    if (forecastEvents.length) {
      await ForecastEvent.insertMany(forecastEvents);
    }

    res.json({
      success: true,
      booking,
      forecastEventsCreated: forecastEvents.length,
    });
  } catch (error) {
    console.error("updateBookingForecast error:", error);
    res.status(500).json({
      success: false,
      message: error.message,
    });
  }
};

export const getBookingForecasts = async (req, res) => {
  try {
    const bookings = await BookingForecast.find()
      .sort({ eventDate: 1 })
      .lean();

    res.json({
      success: true,
      bookings,
    });
  } catch (error) {
    console.error("getBookingForecasts error:", error);
    res.status(500).json({
      success: false,
      message: error.message,
    });
  }
};

export const getBookingForecastById = async (req, res) => {
  try {
    const booking = await BookingForecast.findById(req.params.id).lean();

    if (!booking) {
      return res.status(404).json({
        success: false,
        message: "Booking forecast not found",
      });
    }

    const forecastEvents = await ForecastEvent.find({
      bookingForecastId: booking._id,
    })
      .sort({ expectedDate: 1 })
      .lean();

    res.json({
      success: true,
      booking,
      forecastEvents,
    });
  } catch (error) {
    console.error("getBookingForecastById error:", error);
    res.status(500).json({
      success: false,
      message: error.message,
    });
  }
};

export const deleteBookingForecast = async (req, res) => {
  try {
    const { id } = req.params;

    const booking = await BookingForecast.findByIdAndDelete(id);

    if (!booking) {
      return res.status(404).json({
        success: false,
        message: "Booking forecast not found",
      });
    }

    await ForecastEvent.deleteMany({
      bookingForecastId: id,
      isAutoGenerated: true,
    });

    res.json({
      success: true,
      message: "Booking forecast and generated forecast events deleted",
    });
  } catch (error) {
    console.error("deleteBookingForecast error:", error);
    res.status(500).json({
      success: false,
      message: error.message,
    });
  }
};