import BookingForecast from "../models/bookingForecastModel.js";
import ForecastEvent from "../models/forecastEventModel.js";
import generateForecastEventsFromBooking from "../utils/generateForecastEventsFromBooking.js";
import XLSX from "xlsx";
import getExpectedBalanceDateForSource from "../utils/paymentRules.js";


export const createBookingForecast = async (req, res) => {
  try {
    const booking = await BookingForecast.create(req.body);

    const forecastEvents = generateForecastEventsFromBooking(booking);

    if (forecastEvents.length) {
      await ForecastEvent.insertMany(forecastEvents);
    }

    res.status(201).json({
      success: true,
      booking,
      forecastEventsCreated: forecastEvents.length,
    });
  } catch (error) {
    console.error("createBookingForecast error:", error);
    res.status(500).json({
      success: false,
      message: error.message,
    });
  }
};

export const updateBookingForecast = async (req, res) => {
  try {
    const { id } = req.params;

    const booking = await BookingForecast.findByIdAndUpdate(id, req.body, {
      new: true,
      runValidators: true,
    });

    if (!booking) {
      return res.status(404).json({
        success: false,
        message: "Booking forecast not found",
      });
    }

    // Delete old auto-generated forecast events for this booking
    await ForecastEvent.deleteMany({
      bookingForecastId: booking._id,
      isAutoGenerated: true,
      status: { $in: ["forecast", "confirmed"] },
    });

    // Recreate updated forecast events
    const forecastEvents = generateForecastEventsFromBooking(booking);

    if (forecastEvents.length) {
      await ForecastEvent.insertMany(forecastEvents);
    }

    res.json({
      success: true,
      booking,
      forecastEventsCreated: forecastEvents.length,
    });
  } catch (error) {
    console.error("updateBookingForecast error:", error);
    res.status(500).json({
      success: false,
      message: error.message,
    });
  }
};

export const getBookingForecasts = async (req, res) => {
  try {
    const bookings = await BookingForecast.find().sort({ eventDate: 1 }).lean();

    res.json({
      success: true,
      bookings,
    });
  } catch (error) {
    console.error("getBookingForecasts error:", error);
    res.status(500).json({
      success: false,
      message: error.message,
    });
  }
};

export const getBookingForecastById = async (req, res) => {
  try {
    const booking = await BookingForecast.findById(req.params.id).lean();

    if (!booking) {
      return res.status(404).json({
        success: false,
        message: "Booking forecast not found",
      });
    }

    const forecastEvents = await ForecastEvent.find({
      bookingForecastId: booking._id,
    })
      .sort({ expectedDate: 1 })
      .lean();

    res.json({
      success: true,
      booking,
      forecastEvents,
    });
  } catch (error) {
    console.error("getBookingForecastById error:", error);
    res.status(500).json({
      success: false,
      message: error.message,
    });
  }
};

export const deleteBookingForecast = async (req, res) => {
  try {
    const { id } = req.params;

    const booking = await BookingForecast.findByIdAndDelete(id);

    if (!booking) {
      return res.status(404).json({
        success: false,
        message: "Booking forecast not found",
      });
    }

    await ForecastEvent.deleteMany({
      bookingForecastId: id,
      isAutoGenerated: true,
    });

    res.json({
      success: true,
      message: "Booking forecast and generated forecast events deleted",
    });
  } catch (error) {
    console.error("deleteBookingForecast error:", error);
    res.status(500).json({
      success: false,
      message: error.message,
    });
  }
};

const clean = (value) => String(value || "").trim();

const toNumber = (value) => {
  if (value === undefined || value === null || value === "") return 0;
  const cleaned = String(value).replace(/[£,]/g, "").trim();
  const num = Number(cleaned);
  return Number.isFinite(num) ? num : 0;
};

const toBool = (value) => {
  const v = clean(value).toLowerCase();
  return ["yes", "true", "paid", "done", "checked", "complete"].includes(v);
};

const toDate = (value) => {
  if (!value) return undefined;

  if (value instanceof Date && !Number.isNaN(value.getTime())) return value;

  if (typeof value === "number") {
    const parsed = XLSX.SSF.parse_date_code(value);
    if (!parsed) return undefined;
    return new Date(Date.UTC(parsed.y, parsed.m - 1, parsed.d));
  }

  const d = new Date(value);
  return Number.isNaN(d.getTime()) ? undefined : d;
};

const normaliseHeader = (header) =>
  clean(header).toLowerCase().replace(/\s+/g, " ");

const get = (row, headerMap, name) => {
  const index = headerMap[normaliseHeader(name)];
  return index === undefined ? undefined : row[index];
};

const buildHeaderMap = (row) => {
  const map = {};
  row.forEach((cell, index) => {
    const key = normaliseHeader(cell);
    if (key) map[key] = index;
  });
  return map;
};

const isGigForecastHeaderRow = (row) => {
  const headers = row.map((cell) => normaliseHeader(cell));

  return (
    headers.includes("booking made") &&
    headers.includes("event date") &&
    headers.includes("source")
  );
};

const isHeaderRow = (row) =>
  row.some((cell) => normaliseHeader(cell) === "name") &&
  row.some((cell) => normaliseHeader(cell) === "owner") &&
  row.some((cell) => normaliseHeader(cell) === "event date");

const isGroupRow = (row) => {
  const filled = row.filter((cell) => clean(cell)).length;
  return filled === 1 && clean(row[0]) && !isHeaderRow(row);
};

const buildBookingFromMondayRow = (row, headerMap, mondayGroup) => {
  const eventDate = toDate(get(row, headerMap, "Event Date"));
  const bookingRef = clean(get(row, headerMap, "Ref"));

  const dealValue = toNumber(get(row, headerMap, "Deal Value"));
  const grossBookingValue = toNumber(
    get(row, headerMap, "Gross Booking Value"),
  );
  const ewanFee = toNumber(get(row, headerMap, "Ewan's Fee"));

  return {
    // Core identifiers
    bookingRef,
    mondayItemName: clean(get(row, headerMap, "Name")),
    mondayGroup,
    bookingReferral: clean(get(row, headerMap, "Booking Referral")),

    // CRM ownership + status
    owner: clean(get(row, headerMap, "Owner")),
    stage: clean(get(row, headerMap, "Stage")),
    status: clean(get(row, headerMap, "Status")) || "forecast",

    // Client details
    clientNames:
      clean(get(row, headerMap, "First Names")) ||
      clean(get(row, headerMap, "Name")),
    firstName: clean(get(row, headerMap, "First Name")),
    lastName: clean(get(row, headerMap, "Last Name")),
    clientEmail:
      clean(get(row, headerMap, "Client Email Address")) ||
      clean(get(row, headerMap, "Ref")),
    clientPhone: clean(get(row, headerMap, "Phone Number")),
    postcode: clean(get(row, headerMap, "Zip")),

    // Event details
    eventDate,
    eventDateForEmail: clean(get(row, headerMap, "Event Date for email")),
    eventType: clean(get(row, headerMap, "Event Type")),
    weddingStatus: clean(get(row, headerMap, "Wedding/Non-Wedding")),
    birthdayOrYourName: clean(
      get(row, headerMap, "Birthday Boy/Girl Name or 'your'"),
    ),
    guestsLabel: clean(get(row, headerMap, "Guests")),
    fullAddress: clean(get(row, headerMap, "Address")),

    // Band details
    tscBandName: clean(get(row, headerMap, "TSC Band Name")),
    bookedBandName: clean(get(row, headerMap, "Booked Band Name")),
    actName:
      clean(get(row, headerMap, "TSC Band Name")) ||
      clean(get(row, headerMap, "Booked Band Name")),
    vocalistName: clean(get(row, headerMap, "Vocalist Name")),
    vocalistEmail: clean(get(row, headerMap, "Vocalist Email")),
    bandMembers: clean(get(row, headerMap, "Band Members")),
    bandSize: clean(get(row, headerMap, "Band Size")),
    allocated: clean(get(row, headerMap, "Allocated")),

    // Add-ons / planning
    firstDanceOrOffRepRequest: clean(
      get(row, headerMap, "First Dance / Off-Repertoire Request"),
    ),
    bookedMannedPlaylist: toBool(get(row, headerMap, "Booked Manned Playlist")),
    bookedDj: toBool(get(row, headerMap, "Booked DJ")),

    // Links
    eventSheetLink: clean(get(row, headerMap, "Event Sheet")),
    invoiceLink: clean(get(row, headerMap, "Invoice")),
    whatsappGroupLink: clean(get(row, headerMap, "WhatsApp Group")),

    // Workflow dates
    songSuggestionsDueDate: toDate(
      get(row, headerMap, "Song Suggestions Due Date"),
    ),
    songSuggestionsDueDateForEmail: clean(
      get(row, headerMap, "Song Suggestion due date for email"),
    ),
    eventSheetCompleteDate: toDate(
      get(row, headerMap, "Event Sheet Complete Date"),
    ),
    eventSheetCompleteDateForEmail: clean(
      get(row, headerMap, "Event Sheet complete date for email"),
    ),
    sendDate: toDate(get(row, headerMap, "Send date")),

    // Workflow statuses
    eventSheetStatus: clean(get(row, headerMap, "Event Sheet Status")),
    whatsappGroupSetUp: clean(get(row, headerMap, "WhatsApp Group Set Up")),
    sendIntroEmail: toBool(get(row, headerMap, "Send Intro Email")),
    paid: toBool(get(row, headerMap, "Paid")),
    removeUnsubDoesntWork: toBool(
      get(row, headerMap, "Remove / Unsub / Doesn't Work"),
    ),

    // Reviews / post-event
    dontRequestReview: toBool(get(row, headerMap, "Don't Request Review")),
    review: clean(get(row, headerMap, "Review")),
    givenNonGoogleReview: toBool(
      get(row, headerMap, "Given Non Google Review"),
    ),
    givenGoogleReview: toBool(get(row, headerMap, "Given Google Review")),
    givenPhotosVideos: toBool(get(row, headerMap, "Given Photos/Videos")),
    socialMediaContent: toBool(get(row, headerMap, "Social Media Content")),
    manualReviewRequestSent: toBool(
      get(row, headerMap, "Manual Review Request Sent"),
    ),

    // Finance
    source: clean(get(row, headerMap, "Agent")) || "Other",
    agent: clean(get(row, headerMap, "Agent")),
    dealValue,
    grossBookingValue,
    totalBookingValue: grossBookingValue || dealValue,
    balanceAmount: grossBookingValue || dealValue,
    ewanFee,

    // Notes
    mondayText: clean(get(row, headerMap, "Text")),
    checkbox: toBool(get(row, headerMap, "Checkbox")),
  };
};

export const importMondayBookingForecasts = async (req, res) => {
  try {
    if (!req.file?.buffer) {
      return res.status(400).json({
        success: false,
        message: "No XLSX file uploaded",
      });
    }

    const workbook = XLSX.read(req.file.buffer, {
      type: "buffer",
      cellDates: true,
    });

    const sheetName = workbook.SheetNames[0];
    const sheet = workbook.Sheets[sheetName];

    const rows = XLSX.utils.sheet_to_json(sheet, {
      header: 1,
      defval: "",
      raw: true,
    });

    let currentGroup = "";
    let headerMap = null;

    let imported = 0;
    let updated = 0;
    let skipped = 0;
    let forecastEventsCreated = 0;

    const errors = [];

    for (const row of rows) {
      if (!row || !row.length) continue;

      if (isGroupRow(row)) {
        currentGroup = clean(row[0]);
        continue;
      }

      if (isHeaderRow(row)) {
        headerMap = buildHeaderMap(row);
        continue;
      }

      if (!headerMap) {
        skipped += 1;
        continue;
      }

      const booking = buildBookingFromMondayRow(row, headerMap, currentGroup);

      if (
        !booking.mondayItemName &&
        !booking.clientEmail &&
        !booking.bookingRef
      ) {
        skipped += 1;
        continue;
      }

      try {
       const query = booking.bookingRef
  ? {
      $or: [
        { bookingRef: booking.bookingRef },
        {
          clientNames: booking.clientNames,
          actName: booking.actName,
          eventDate: booking.eventDate,
        },
      ],
    }
  : {
      clientNames: booking.clientNames,
      actName: booking.actName,
      eventDate: booking.eventDate,
    };

        const existing = await BookingForecast.findOne(query);

        const savedBooking = existing
          ? await BookingForecast.findByIdAndUpdate(existing._id, booking, {
              new: true,
              runValidators: true,
            })
          : await BookingForecast.create(booking);

        if (existing) updated += 1;
        else imported += 1;

       

        const today = new Date();
        today.setHours(0, 0, 0, 0);

        if (
          savedBooking.eventDate &&
          new Date(savedBooking.eventDate) >= today
        ) {
          const generatedEvents =
            generateForecastEventsFromBooking(savedBooking);

          if (generatedEvents.length) {
            await ForecastEvent.insertMany(generatedEvents);
            forecastEventsCreated += generatedEvents.length;
          }
        }
      } catch (rowError) {
        errors.push({
          rowName: booking.mondayItemName,
          message: rowError.message,
        });
      }
    }

    res.json({
      success: true,
      sheetName,
      imported,
      updated,
      skipped,
      forecastEventsCreated,
      errors,
    });
  } catch (error) {
    console.error("importMondayBookingForecasts error:", error);
    res.status(500).json({
      success: false,
      message: error.message,
    });
  }
};

export const buildBookingFromGigForecastRow = (row, headerMap) => {
  const bookingMadeDate = toDate(get(row, headerMap, "Booking Made"));
  const eventDate = toDate(get(row, headerMap, "Event Date"));

  const depositAmount =
    toNumber(get(row, headerMap, "TSC Deposit")) ||
    toNumber(get(row, headerMap, "In BBM / Deposit In Barc"));

  const totalBookingValue = toNumber(get(row, headerMap, "Total"));
  const balanceAmount =
    toNumber(get(row, headerMap, "Subtotal (after deposit taken) / Balance")) ||
    Math.max(totalBookingValue - depositAmount, 0);

  const transactionDate = toDate(get(row, headerMap, "Date of transaction"));

  return {
    bookingMadeDate,
    bookingRef: clean(get(row, headerMap, "Ref")),
    eventDate,

    source: clean(get(row, headerMap, "Source")) || "Other",
    clientNames: clean(get(row, headerMap, "First Names")),

    allocated: clean(get(row, headerMap, "Allocated")),
    groupChatSetUp: toBool(get(row, headerMap, "Group Chat Set up?")),
    setlistSharedOnGroupChat: toBool(
      get(row, headerMap, "Setlist shared on group chat"),
    ),
    balancePaid: toBool(get(row, headerMap, "Balance Paid")),

    outstandingPoints: clean(get(row, headerMap, "Outstanding points")),
    eventSheetLink: clean(get(row, headerMap, "Event Sheet Link")),

    eventType: clean(get(row, headerMap, "Event Type")),
    tscBandName: clean(get(row, headerMap, "TSC Band Name")),
    actName: clean(get(row, headerMap, "TSC Band Name")),
    county: clean(get(row, headerMap, "County")),
    teamStatus: clean(get(row, headerMap, "Team")),
    fullAddress: clean(get(row, headerMap, "Full Address")),
    lineup: clean(get(row, headerMap, "Lineup")),
    leadSingers: clean(get(row, headerMap, "Lead singer(s)")),

    depositAmount,
    totalBookingValue,
    balanceAmount,

    expectedDepositDate: bookingMadeDate,
    expectedBalanceDate:
  transactionDate ||
  getExpectedBalanceDateForSource({
    source: clean(get(row, headerMap, "Source")) || "Other",
    eventDate,
    bookingMadeDate,
  }) ||
  eventDate,
    actualBalanceDate: toBool(get(row, headerMap, "Balance Paid"))
      ? transactionDate || eventDate
      : undefined,

    ewanFee: toNumber(get(row, headerMap, "Ewan's Fee")),
    bmmFee: toNumber(get(row, headerMap, "To BMM")),
    commissionAmount: toNumber(get(row, headerMap, "BBM Total")),

    mondayText: clean(get(row, headerMap, "Mail Merge Status")),
    notes: clean(get(row, headerMap, "File Attachments")),
    status: "confirmed",
  };
};

export const importGigForecastBookings = async (req, res) => {
  try {
    if (!req.file?.buffer) {
      return res.status(400).json({
        success: false,
        message: "No XLSX file uploaded",
      });
    }

    const workbook = XLSX.read(req.file.buffer, {
      type: "buffer",
      cellDates: true,
    });

    const sheetName = workbook.SheetNames[0];
    const sheet = workbook.Sheets[sheetName];

    const rows = XLSX.utils.sheet_to_json(sheet, {
      header: 1,
      defval: "",
      raw: true,
    });

    let headerMap = null;

    let imported = 0;
    let updated = 0;
    let skipped = 0;
    let forecastEventsCreated = 0;

    const errors = [];

    for (const row of rows) {
      if (!row || !row.length) continue;

      if (isGigForecastHeaderRow(row)) {
        headerMap = buildHeaderMap(row);
        console.log("Gig forecast headerMap:", headerMap);
        continue;
      }

      if (!headerMap) {
        skipped += 1;
        continue;
      }

      const hasUsefulRowData = row.some((cell) => clean(cell));

      if (!hasUsefulRowData) {
        skipped += 1;
        continue;
      }

      const booking = buildBookingFromGigForecastRow(row, headerMap);

      const eventYear = booking.eventDate
        ? new Date(booking.eventDate).getFullYear()
        : null;

      if (![2026, 2027].includes(eventYear)) {
        skipped += 1;
        continue;
      }

      if (!booking.eventDate || !booking.clientNames || !booking.actName) {
        skipped += 1;
        continue;
      }

      try {
       const query =
  booking.bookingRef
    ? {
        $or: [
          { bookingRef: booking.bookingRef },
          {
            clientNames: booking.clientNames,
            actName: booking.actName,
            eventDate: booking.eventDate,
          },
        ],
      }
    : {
        clientNames: booking.clientNames,
        actName: booking.actName,
        eventDate: booking.eventDate,
      };

        const existing = await BookingForecast.findOne(query);

        const savedBooking = existing
          ? await BookingForecast.findByIdAndUpdate(existing._id, booking, {
              new: true,
              runValidators: true,
            })
          : await BookingForecast.create(booking);

        if (existing) updated += 1;
        else imported += 1;

await ForecastEvent.deleteMany({
  isAutoGenerated: true,
  source: { $ne: "recurring_rule" },
  status: { $in: ["forecast", "confirmed"] },
  $or: [
    { bookingForecastId: savedBooking._id },
    {
      clientNames: savedBooking.clientNames,
      actName: savedBooking.actName,
      eventDate: savedBooking.eventDate,
    },
  ],
});

        const generatedEvents = generateForecastEventsFromBooking(savedBooking);

        if (generatedEvents.length) {
          await ForecastEvent.insertMany(generatedEvents);
          forecastEventsCreated += generatedEvents.length;
        }
      } catch (rowError) {
        errors.push({
          rowName: booking.clientNames,
          ref: booking.bookingRef,
          message: rowError.message,
        });
      }
    }

    res.json({
      success: true,
      sheetName,
      imported,
      updated,
      skipped,
      forecastEventsCreated,
      errors,
    });
  } catch (error) {
    console.error("importGigForecastBookings error:", error);
    res.status(500).json({
      success: false,
      message: error.message,
    });
  }
};
