import RecurringForecastRule from "../models/recurringForecastRuleModel.js";
import ForecastEvent from "../models/forecastEventModel.js";

const addMonthsSafe = (date, monthsToAdd, preferredDay) => {
  const d = new Date(date);
  const year = d.getUTCFullYear();
  const month = d.getUTCMonth() + monthsToAdd;

  const firstOfTargetMonth = new Date(Date.UTC(year, month, 1));
  const lastDay = new Date(
    Date.UTC(
      firstOfTargetMonth.getUTCFullYear(),
      firstOfTargetMonth.getUTCMonth() + 1,
      0,
    ),
  ).getUTCDate();

  const day = Math.min(preferredDay || d.getUTCDate(), lastDay);

  return new Date(
    Date.UTC(
      firstOfTargetMonth.getUTCFullYear(),
      firstOfTargetMonth.getUTCMonth(),
      day,
    ),
  );
};

const addFrequency = (date, frequency, count, rule = {}) => {
  const d = new Date(date);

  if (frequency === "weekly") {
    const next = new Date(d);
    next.setUTCDate(next.getUTCDate() + 7 * count);
    return next;
  }

  if (frequency === "monthly") {
    return addMonthsSafe(d, count, rule.dayOfMonth);
  }

  if (frequency === "quarterly") {
    return addMonthsSafe(d, count * 3, rule.dayOfMonth);
  }

  if (frequency === "yearly") {
    return addMonthsSafe(d, count * 12, rule.dayOfMonth);
  }

  return d;
};

const buildGeneratedForecastEvent = (rule, expectedDate) => ({
  recurringRuleId: rule._id,
  entity: rule.entity,
  type: rule.type,
  title: rule.title,
  description: rule.description,
  expectedDate,
  amount: Math.abs(Number(rule.amount || 0)),
  direction: rule.direction,
  status: "forecast",
  source: "recurring_rule",
  isAutoGenerated: true,
  notes: rule.notes,
});

export const createRecurringForecastRule = async (req, res) => {
  try {
    const rule = await RecurringForecastRule.create(req.body);

    res.status(201).json({
      success: true,
      rule,
    });
  } catch (error) {
    console.error("createRecurringForecastRule error:", error);
    res.status(500).json({ success: false, message: error.message });
  }
};

export const getRecurringForecastRules = async (req, res) => {
  try {
    const { entity, status } = req.query;

    const query = {};
    if (entity) query.entity = entity;
    if (status) query.status = status;

    const rules = await RecurringForecastRule.find(query)
      .sort({ entity: 1, title: 1 })
      .lean();

    res.json({
      success: true,
      rules,
    });
  } catch (error) {
    console.error("getRecurringForecastRules error:", error);
    res.status(500).json({ success: false, message: error.message });
  }
};

export const getRecurringForecastRuleById = async (req, res) => {
  try {
    const rule = await RecurringForecastRule.findById(req.params.id).lean();

    if (!rule) {
      return res.status(404).json({
        success: false,
        message: "Recurring forecast rule not found",
      });
    }

    res.json({
      success: true,
      rule,
    });
  } catch (error) {
    console.error("getRecurringForecastRuleById error:", error);
    res.status(500).json({ success: false, message: error.message });
  }
};

export const updateRecurringForecastRule = async (req, res) => {
  try {
    const rule = await RecurringForecastRule.findByIdAndUpdate(
      req.params.id,
      req.body,
      { new: true, runValidators: true },
    );

    if (!rule) {
      return res.status(404).json({
        success: false,
        message: "Recurring forecast rule not found",
      });
    }

    res.json({
      success: true,
      rule,
    });
  } catch (error) {
    console.error("updateRecurringForecastRule error:", error);
    res.status(500).json({ success: false, message: error.message });
  }
};

export const deleteRecurringForecastRule = async (req, res) => {
  try {
    const rule = await RecurringForecastRule.findByIdAndDelete(req.params.id);

    if (!rule) {
      return res.status(404).json({
        success: false,
        message: "Recurring forecast rule not found",
      });
    }

    res.json({
      success: true,
      message: "Recurring forecast rule deleted",
    });
  } catch (error) {
    console.error("deleteRecurringForecastRule error:", error);
    res.status(500).json({ success: false, message: error.message });
  }
};

export const generateForecastEventsFromRecurringRules = async (req, res) => {
  try {
    const {
      entity,
      months = 12,
      replaceExisting = true,
    } = req.body;

    const query = { status: "active" };
    if (entity) query.entity = entity;

    const rules = await RecurringForecastRule.find(query);

    const now = new Date();
    const horizonEnd = addMonthsSafe(now, Number(months || 12), now.getUTCDate());

    if (replaceExisting) {
      await ForecastEvent.deleteMany({
        source: "recurring_rule",
        isAutoGenerated: true,
        status: { $in: ["forecast", "confirmed"] },
        ...(entity ? { entity } : {}),
      });
    }

    const eventsToInsert = [];

    for (const rule of rules) {
      let occurrence = new Date(rule.startDate);
      let count = 0;

      while (occurrence < now && count < 1000) {
        count += 1;
        occurrence = addFrequency(rule.startDate, rule.frequency, count, rule);
      }

      while (
        occurrence <= horizonEnd &&
        (!rule.endDate || occurrence <= new Date(rule.endDate)) &&
        count < 2000
      ) {
        eventsToInsert.push(buildGeneratedForecastEvent(rule, occurrence));

        count += 1;
        occurrence = addFrequency(rule.startDate, rule.frequency, count, rule);
      }
    }

    const createdEvents = eventsToInsert.length
      ? await ForecastEvent.insertMany(eventsToInsert)
      : [];

    res.json({
      success: true,
      rulesProcessed: rules.length,
      eventsCreated: createdEvents.length,
      events: createdEvents,
    });
  } catch (error) {
    console.error("generateForecastEventsFromRecurringRules error:", error);
    res.status(500).json({ success: false, message: error.message });
  }
};