const toNumber = (value) => {
  const num = Number(value);
  return Number.isFinite(num) ? num : 0;
};

const hasDate = (value) => value && !Number.isNaN(new Date(value).getTime());

const buildTitle = (prefix, booking = {}) => {
  const client = booking.clientNames || booking.firstName || "Client";
  const act = booking.actName || booking.tscBandName || booking.bookedBandName || "Booking";
  return `${prefix} - ${client} / ${act}`;
};

const getBookingEntity = (booking = {}) => {
  // For now, keep it simple. Later we can make this source/payment-rule driven.
  if (booking.source === "Direct" || booking.source === "TSC") return "TSC";
  return "BMM";
};

const createEvent = ({
  booking,
  type,
  title,
  expectedDate,
  amount,
  direction,
  entity,
  description,
  notes,
}) => ({
  bookingForecastId: booking._id,
  entity,
  type,
  title,
  description,
  expectedDate,
  amount: Math.abs(toNumber(amount)),
  direction,
  status: "forecast",
  source: booking.source,
  clientNames: booking.clientNames,
  actName: booking.actName || booking.tscBandName || booking.bookedBandName,
  eventDate: booking.eventDate,
  isAutoGenerated: true,
  notes,
});

export const generateForecastEventsFromBooking = (booking = {}) => {
  const events = [];

  const entity = getBookingEntity(booking);

  const depositAmount = toNumber(booking.depositAmount);
  const balanceAmount = toNumber(booking.balanceAmount);
  const totalBookingValue = toNumber(booking.totalBookingValue);
  const grossBookingValue = toNumber(booking.grossBookingValue);
  const dealValue = toNumber(booking.dealValue);

  const fallbackBalance =
    balanceAmount ||
    Math.max(totalBookingValue - depositAmount, 0) ||
    grossBookingValue ||
    dealValue;

  if (depositAmount > 0 && !booking.depositPaid) {
    const expectedDate =
      booking.expectedDepositDate ||
      booking.bookingMadeDate ||
      booking.createdAt ||
      new Date();

    if (hasDate(expectedDate)) {
      events.push(
        createEvent({
          booking,
          entity,
          type: "client_deposit_in",
          title: buildTitle("Deposit expected", booking),
          expectedDate,
          amount: depositAmount,
          direction: "in",
        }),
      );
    }
  }

  if (fallbackBalance > 0 && !booking.balancePaid) {
    const expectedDate =
      booking.expectedBalanceDate ||
      booking.eventDate;

    if (hasDate(expectedDate)) {
      events.push(
        createEvent({
          booking,
          entity,
          type: "client_balance_in",
          title: buildTitle("Balance expected", booking),
          expectedDate,
          amount: fallbackBalance,
          direction: "in",
        }),
      );
    }
  }

  if (Array.isArray(booking.supplierPayments)) {
    booking.supplierPayments.forEach((payment) => {
      const amount = toNumber(payment.amount);
      if (amount <= 0 || payment.paid) return;

      const expectedDate =
        payment.expectedPaymentDate ||
        booking.eventDate;

      if (!hasDate(expectedDate)) return;

      events.push(
        createEvent({
          booking,
          entity,
          type: "supplier_payment_out",
          title: `Supplier payment - ${payment.name || payment.role || "TBC"}`,
          description: buildTitle("Supplier payout", booking),
          expectedDate,
          amount,
          direction: "out",
          notes: payment.notes,
        }),
      );
    });
  }

  return events;
};

export default generateForecastEventsFromBooking;