import getExpectedBalanceDateForSource from "./paymentRules.js";

const toNumber = (value) => {
  const num = Number(value);
  return Number.isFinite(num) ? num : 0;
};

const hasDate = (value) => value && !Number.isNaN(new Date(value).getTime());

const buildTitle = (prefix, booking = {}) => {
  const client = booking.clientNames || booking.firstName || "Client";
  const act = booking.actName || booking.tscBandName || booking.bookedBandName || "Booking";
  return `${prefix} - ${client} / ${act}`;
};

const getBookingEntity = (booking = {}) => {
  // For now, keep it simple. Later we can make this source/payment-rule driven.
  if (booking.source === "Direct" || booking.source === "TSC") return "TSC";
  return "BMM";
};

const VAT_REGISTRATION_DATES = {
  BMM: new Date("2026-02-01T00:00:00.000Z"),
  TSC: null, // add date here once TSC is VAT registered
};

const isVatRegisteredOnDate = (entity, date) => {
  const registrationDate = VAT_REGISTRATION_DATES[entity];
  if (!registrationDate || !date) return false;

  return new Date(date) >= registrationDate;
};

const isClientIncomeType = (type) =>
  ["client_deposit_in", "client_balance_in"].includes(type);

const createEvent = ({
  booking,
  type,
  title,
  expectedDate,
  amount,
  direction,
  entity,
  description,
  notes,
}) => {
  const isClientIncome =
    direction === "in" &&
    ["client_deposit_in", "client_balance_in"].includes(type);

  const appliesVat =
    isClientIncome && isVatRegisteredOnDate(entity, expectedDate);

  const vatableAmount =
    booking.commissionAmount ||
    booking.bmmFee ||
    booking.rhonaFee ||
    0;

  return {
    bookingForecastId: booking._id,
    entity,
    type,
    title,
    description,
    expectedDate,
    amount: Math.abs(toNumber(amount)),
    direction,
    status: "forecast",
    source: booking.source,
    clientNames: booking.clientNames,
    actName: booking.actName || booking.tscBandName || booking.bookedBandName,
    eventDate: booking.eventDate,
    isAutoGenerated: true,
    notes,

    vatTreatment: appliesVat ? "standard" : "outside_scope",
    vatRate: appliesVat ? 0.2 : 0,
    vatBasis: appliesVat ? "commission" : "outside_scope",
    vatableAmount: appliesVat ? Math.abs(toNumber(vatableAmount)) : 0,

    taxTreatment: direction === "in" ? "income" : "expense",
  };
};

export const generateForecastEventsFromBooking = (booking = {}) => {
  const events = [];

  const entity = getBookingEntity(booking);

  const depositAmount = toNumber(booking.depositAmount);
  const balanceAmount = toNumber(booking.balanceAmount);
  const totalBookingValue = toNumber(booking.totalBookingValue);
  const grossBookingValue = toNumber(booking.grossBookingValue);
  const dealValue = toNumber(booking.dealValue);

  const fallbackBalance =
    balanceAmount ||
    Math.max(totalBookingValue - depositAmount, 0) ||
    grossBookingValue ||
    dealValue;

  if (depositAmount > 0 && !booking.depositPaid) {
    const expectedDate =
      booking.expectedDepositDate ||
      booking.bookingMadeDate ||
      booking.createdAt ||
      new Date();

    if (hasDate(expectedDate)) {
      events.push(
        createEvent({
          booking,
          entity,
          type: "client_deposit_in",
          title: buildTitle("Deposit expected", booking),
          expectedDate,
          amount: depositAmount,
          direction: "in",
        }),
      );
    }
  }

  if (fallbackBalance > 0 && !booking.balancePaid) {
  const expectedDate =
  booking.expectedBalanceDate ||
  getExpectedBalanceDateForSource({
    source: booking.source || booking.agent,
    eventDate: booking.eventDate,
    bookingMadeDate: booking.bookingMadeDate || booking.createdAt,
  }) ||
  booking.eventDate;

    if (hasDate(expectedDate)) {
      events.push(
        createEvent({
          booking,
          entity,
          type: "client_balance_in",
          title: buildTitle("Balance expected", booking),
          expectedDate,
          amount: fallbackBalance,
          direction: "in",
        }),
      );
    }
  }

if (Array.isArray(booking.supplierPayments)) {
  booking.supplierPayments.forEach((payment) => {
    const paymentName = String(payment.name || payment.role || "").trim();
    const paymentNameLower = paymentName.toLowerCase();

    // BMM is retained commission/management fee, not a supplier payout
    if (["bmm", "bamboo music management"].includes(paymentNameLower)) {
      return;
    }

    const amount = toNumber(payment.amount);
    if (amount <= 0 || payment.paid) return;

    const expectedDate = payment.expectedPaymentDate || booking.eventDate;

    if (!hasDate(expectedDate)) return;

    events.push(
      createEvent({
        booking,
        entity,
        type: "supplier_payment_out",
        title: `Supplier payment - ${payment.name || payment.role || "TBC"}`,
        description: buildTitle("Supplier payout", booking),
        expectedDate,
        amount,
        direction: "out",
        notes: payment.notes,
      }),
    );
  });
}

  return events;
};


export default generateForecastEventsFromBooking;
