import mongoose from "mongoose";

const forecastEventSchema = new mongoose.Schema(
  {
    bookingForecastId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "BookingForecast",
    },

    accountId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "FinanceAccount",
    },

    entity: {
      type: String,
      enum: [
        "TSC",
        "BMM",
        "HSBC",
        "Monzo Joint",
        "Monzo Personal",
        "AMEX",
        "CBS",
        "HL Investment",
        "HSBC Investment",
        "Bitcoin",
        "Solana",
        "Ethereum",
        "True Potential Penson",
        "Aviva Pension",
      ],
      required: true,
    },

    type: {
      type: String,
      enum: [
        "client_deposit_in",
        "client_balance_in",
        "supplier_payment_out",
        "salary_out",
        "ni_out",
        "vat_out",
        "corporation_tax_out",
        "recurring_income",
        "recurring_expense",
        "manual_adjustment",
      ],
      required: true,
    },

    title: { type: String, trim: true },
    description: String,

    expectedDate: { type: Date, required: true },
    actualDate: Date,

    amount: { type: Number, required: true },

    direction: {
      type: String,
      enum: ["in", "out"],
      required: true,
    },

    status: {
      type: String,
      enum: ["forecast", "confirmed", "paid", "cancelled", "ignored"],
      default: "forecast",
    },
    actualTransactionId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "FinanceTransaction",
    },
    recurringRuleId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "RecurringForecastRule",
    },
    vatTreatment: {
      type: String,
      default: "outside_scope",
      enum: ["standard", "zero", "exempt", "outside_scope", "unknown"],
    },
    vatRate: {
      type: Number,
      default: 0,
    },
    taxTreatment: {
      type: String,
      default: "unknown",
    },
    vatBasis: {
      type: String,
      default: "outside_scope",
      enum: ["gross", "commission", "outside_scope", "unknown"],
    },
    vatableAmount: {
      type: Number,
      default: 0,
    },
    source: String,

bookingRef: {
  type: String,
  trim: true,
  index: true,
},

clientNames: String,
actName: String,
eventDate: Date,

    isAutoGenerated: { type: Boolean, default: true },
    notes: String,
  },
  { timestamps: true },
);

forecastEventSchema.index({ expectedDate: 1 });
forecastEventSchema.index({ entity: 1 });
forecastEventSchema.index({ bookingForecastId: 1 });
forecastEventSchema.index({ status: 1 });

const ForecastEvent =
  mongoose.models.ForecastEvent ||
  mongoose.model("ForecastEvent", forecastEventSchema);

export default ForecastEvent;
